name: breedward
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0+3

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  ionicons: ^0.2.1
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_database: ^11.3.5
  lottie: ^3.3.1
  google_sign_in: any
  permission_handler: ^11.4.0
  fluttertoast: ^8.2.12
  fl_chart: ^0.70.2
  intl: ^0.18.1
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  flutter_local_notifications: ^19.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/iconv2.png"

flutter:
  uses-material-design: true
  assets:
    - assets/places/
    - assets/icons/
    - assets/
    - assets/welcome_man.png
    - assets/loading.json
    - assets/emailforgot.json
    - assets/confthanks.json
